### ISSUE TITLE
Cannot launch botpress bot after cloning

### ISSUE THREAD

**Issue by iannech** [botpress/tutorial#10]
Getting an error when trying to start botpress after cloning the botpress repo from this link https://github.com/botpress/tutorial.git

> botpress start

      You're using the old logs configuration format.
      Since v11 botpress has stopped storing logs in files and
      has moved them to the database.

      Please update your botfile.

      Old configuration format:
        /*
          By default logs are enabled and available in dataDir
        */
        disableFileLogs: false,
        log: {
          file: 'bot.log',
          maxSize: 1e6 // 1mb
        }

      New format:
        /*
          By default logs are enabled and stored in the DB for 30 days
        */
        logs: {
          enabled: true,
          keepDays: 30
        }

D:\workspace_bot\test\tutorial\step-1\node_modules\botpress\src\botpress.js:122
    throw new Error('Outdated botfile format')
          ^
Error: Outdated botfile format
    at validateBotfile (D:\workspace_bot\test\tutorial\step-1\node_modules\botpress\src\botpress.js:122:11)
    at new botpress (D:\workspace_bot\test\tutorial\step-1\node_modules\botpress\src\botpress.js:149:5)
    at Command.module.exports (D:\workspace_bot\test\tutorial\step-1\node_modules\botpress\src\cli\start.js:93:17)
    at Command.listener (D:\workspace_bot\test\tutorial\step-1\node_modules\commander\index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (D:\workspace_bot\test\tutorial\step-1\node_modules\commander\index.js:651:12)
    at Command.parse (D:\workspace_bot\test\tutorial\step-1\node_modules\commander\index.js:474:21)
    at Object.<anonymous> (D:\workspace_bot\test\tutorial\step-1\node_modules\botpress\src\cli\index.js:104:4)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tutorial@1.0.0 start: `botpress start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tutorial@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\INECHENJE\AppData\Roaming\npm-cache\_logs\2018-07-16T11_27_59_068Z-debug.log

How do I resolve this?

**Comment by rschuetzler** [comment]
It tells you how to resolve it in the error message. In your `step-1/botfile.js` file, replace this section:

```
disableFileLogs: false,
    log: {
      file: 'bot.log',
      maxSize: 1e6 // 1mb
    }
```

with this:

```
logs: {
      enabled: true,
      keepDays: 30
    }
```
